addons: 
  apt: 
    packages: 
      - gcc
      - build-essential
    sources: 
      - ubuntu-toolchain-r-test
compiler: 
  - gcc
dist: bionic
os: linux
language: 
  - cpp
script: 
  - "git clone -b pie-gsi https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9"
  - "mkdir out"
  - "export CROSS_COMPILE=/home/travis/build/hackslashX/android_kernel_hisi_hi3650/aarch64-linux-android-4.9/bin/aarch64-linux-android-"
  - "export ARCH=arm64"
  - "export KBUILD_BUILD_USER=\"travis_auto\""
  - "make O=out merge_hi3650_defconfig"
  - "make O=out -j$(nproc --all)"
