# hisilicon ivp

ccflags-$(CONFIG_IVP_VP5) += -Idrivers/hisi/ivp/vp5

obj-$(CONFIG_IVP_VP5) += vp5/ 
obj-$(CONFIG_IVP_SMMU)      += ivp_smmu.o
obj-$(CONFIG_IVP_SMMU_TEST) += ivp_smmu_test.o
obj-$(CONFIG_HISI_IVP) += ivp_ipc.o
obj-$(CONFIG_HISI_IVP) += ivp_core.o
obj-$(CONFIG_HISI_IVP) += ivp_mntn.o
